In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [44]:
df = pd.read_csv('test.txt',sep=";",header=None,names=['text','emotion'])
df.head()

                                                text  emotion
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [45]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [46]:
emotions = df['emotion'].unique()

In [47]:
emo_map = {}
for i, emotion in enumerate(emotions):
    emo_map[emotion] = i
emo_map

{'sadness': 0, 'joy': 1, 'fear': 2, 'anger': 3, 'love': 4, 'surprise': 5}

In [48]:
df['emotion'] = df['emotion'].map(emo_map)
df.head()

                                                text  emotion
0  im feeling rather rotten so im not very ambiti...        0
1          im updating my blog because i feel shitty        0
2  i never make her separate from me because i do...        0
3  i left with my bouquet of red and yellow tulip...        1
4    i was feeling a little vain when i did this one        0

### Text Lowercasing

In [49]:
df['text'] = df['text'].apply(lambda x: x.lower())

### Text Cleaning

* Removing Punctuations
* Removing Numbers
* Removing URLs/Links
* Removing HTML Tags (if web scraping is done)
* Removing Emojis & Special chars
* Removing Stopwords

In [50]:
#creating function
import string

def remove_punc(txt):
    return txt.translate(str.maketrans('', '', string.punctuation))

In [51]:
df['text'] = df['text'].apply(remove_punc)

In [52]:
def remove_num(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new+i
    return new

In [53]:
df['text'] = df['text'].apply(remove_num)

In [54]:
def remove_emo(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new = new+i
    return new

In [55]:
df['text'] = df['text'].apply(remove_emo)

### Removing Stopwords

via NLTK

In [56]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [57]:
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\LENOVO\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [58]:
stop_words = set(stopwords.words('english'))

In [59]:
def remove_stop(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if i not in stop_words:
            cleaned.append(i)
    return ' '.join(cleaned)

In [60]:
df['text'] = df['text'].apply(remove_stop)

In [62]:
df.loc[0]['text']

'im feeling rather rotten im ambitious right'